/*
 * This file is part of the Illarion project.
 *
 * Copyright © 2016 - Illarion e.V.
 *
 * Illarion is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Illarion is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */
apply plugin: 'java-library'
apply plugin: 'application'
apply plugin: 'maven-publish'
apply plugin: 'idea'

apply from: '../versions.gradle'

base { archivesName = 'illarion_easynpc' }
application { mainClass = 'illarion.easynpc.gui.MainFrame' }

project.extensions.antlr = [
        grammarpackage: "illarion.easynpc.grammar",
        antlrSource   : 'src/main/antlr4',
        destinationDir: "src/generated/java"
]

idea {
    module {
        sourceDirs += file(antlr.destinationDir)
    }
}

configurations {
    antlr4 {
        description = "ANTLR4"
    }
}

dependencies {
    api project(':common')
    api "org.slf4j:slf4j-api:${project.ext.slf4jVersion}"
    api "org.slf4j:jul-to-slf4j:${project.ext.slf4jVersion}"
    api "org.slf4j:jcl-over-slf4j:${project.ext.slf4jVersion}"
    api "org.slf4j:log4j-over-slf4j:${project.ext.slf4jVersion}"
    api "ch.qos.logback:logback-classic:${project.ext.logbackVersion}"
    api "org.bushe:eventbus:1.4"
    api "com.github.insubstantial:substance:${project.ext.insubstantialVersion}"
    api "com.github.insubstantial:substance-flamingo:${project.ext.insubstantialVersion}"
    api "com.fifesoft:rsyntaxtextarea:4.0.1"
    api "com.fifesoft:autocomplete:4.0.0"
    api "org.antlr:antlr4-runtime:4.7"

    antlr4 "org.antlr:antlr4:4.7"

    runtimeOnly "org.illarion:rsc_tables:${project.ext.illarionResourcesVersion}"
}

task antlrOutputDir {
    doFirst {
        mkdir(antlr.destinationDir)
    }
}

task generateGrammarSource(dependsOn: antlrOutputDir, type: JavaExec) {
    description = 'Generates Java sources from ANTLR4 grammars.'

    def grammars = fileTree(antlr.antlrSource).include('**/*.g4')
    def pkg = antlr.grammarpackage.replaceAll("\\.", "/")
    def outputDir = "${antlr.destinationDir}/${pkg}"

    inputs.files grammars.files
    outputs.dir file(outputDir)

    mainClass = 'org.antlr.v4.Tool'
    classpath = configurations.antlr4

    args = ["-o", "${outputDir}"/*, "-atn"*/, "-visitor", "-package", antlr.grammarpackage, grammars.files].flatten()

}

tasks.withType(com.github.spotbugs.snom.SpotBugsTask) {
    excludeFilter = file("$projectDir/findbugs-exclude.xml")
}

tasks.withType(Pmd) {
    exclude '**/illarion/easynpc/grammar/*'
}

compileJava {
    dependsOn generateGrammarSource
    source antlr.destinationDir
}

jar {
    dependsOn { gitVersion }
    manifest {
        attributes          \
                 'Main-Class': 'illarion.easynpc.gui.MainFrame',         \
                 'Permissions': 'all-permissions',         \
                 'Codebase': 'illarion.org',         \
                 'Application-Name': 'Illarion easyNPC editor',         \
                 'Application-Library-Allowable-Codebase': 'illarion.org',         \
                 'Built-Date': new Date().format('yyyy-MM-dd HH:mm:ssZ'),         \
                 'Built-By': System.getProperty('user.name'),          \
                 'Built-JDK': System.getProperty('java.version'),          \
                 'Implementation-Title': 'Illarion easyNPC Editor',          \
                 'Implementation-Vendor': 'Illarion e.V.',         \
                 'Implementation-Version': project.ext.fullVersion
    }
}

clean {
    delete antlr.destinationDir
}

task sourceJar(type: Jar) {
    from sourceSets.main.allJava
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java

            artifact sourceJar {
                archiveClassifier = "sources"
            }
        }
    }
    repositories {
        maven {
            url = uri(project.ext.mavenRepo)
        }
    }
}
