/*
 * This file is part of the Illarion project.
 *
 * Copyright © 2016 - Illarion e.V.
 *
 * Illarion is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Illarion is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */
apply plugin: 'java-library'
apply plugin: 'application'
apply plugin: 'maven-publish'

apply from: '../versions.gradle'

base { archivesName = 'illarion_client' }
application { mainClass = 'illarion.client.IllaClient' }

dependencies {
    api project(':common')
    api project(':engine')
    runtimeOnly project(':engine-libgdx')
    api project(':engine-nifty')
    api project(':nifty-controls')
    runtimeOnly project(':nifty-style')
    api "org.slf4j:slf4j-api:${project.ext.slf4jVersion}"
    api "org.slf4j:jul-to-slf4j:${project.ext.slf4jVersion}"
    api "org.slf4j:jcl-over-slf4j:${project.ext.slf4jVersion}"
    api "org.slf4j:log4j-over-slf4j:${project.ext.slf4jVersion}"
    api "ch.qos.logback:logback-classic:${project.ext.logbackVersion}"
    api "org.bushe:eventbus:1.4"
    api "com.google.code.gson:gson:2.8.0"
    api "com.google.guava:guava:21.0"
    api "com.github.nifty-gui:nifty:${project.ext.niftyGuiVersion}"
    runtimeOnly "org.illarion:rsc_books:${project.ext.illarionResourcesVersion}"
    runtimeOnly "org.illarion:rsc_chars:${project.ext.illarionResourcesVersion}"
    runtimeOnly "org.illarion:rsc_effects:${project.ext.illarionResourcesVersion}"
    runtimeOnly "org.illarion:rsc_gui:${project.ext.illarionResourcesVersion}"
    runtimeOnly "org.illarion:rsc_items:${project.ext.illarionResourcesVersion}"
    runtimeOnly "org.illarion:rsc_music:${project.ext.illarionResourcesVersion}"
    runtimeOnly "org.illarion:rsc_sounds:${project.ext.illarionResourcesVersion}"
    runtimeOnly "org.illarion:rsc_tables:${project.ext.illarionResourcesVersion}"
    runtimeOnly "org.illarion:rsc_tiles:${project.ext.illarionResourcesVersion}"
}

jar {
    dependsOn { gitVersion }
    manifest {
        attributes(
                'Main-Class': 'illarion.client.IllaClient',
                'Permissions': 'all-permissions',
                'Codebase': 'illarion.org',
                'Application-Name': 'Illarion Client',
                'Application-Library-Allowable-Codebase': 'illarion.org',
                'Built-Date': new Date().format('yyyy-MM-dd HH:mm:ssZ'),
                'Built-By': System.getProperty('user.name'),
                'Built-JDK': System.getProperty('java.version'),
                'Implementation-Title': 'Illarion Client',
                'Implementation-Vendor': 'Illarion e.V.',
                'Implementation-Version': project.ext.fullVersion,
                'Source-Branch': project.ext.branch,
        )
    }
}

run {
    jvmArgs '-Dillarion.server=devserver'
    doFirst {
        if (javaLauncher.get().metadata.languageVersion.asInt() >= 17) {
            jvmArgs '--enable-native-access=ALL-UNNAMED'
        }
    }
}

task sourceJar(type: Jar) {
    from sourceSets.main.allJava
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java

            artifact sourceJar {
                archiveClassifier = "sources"
            }
        }
    }
    repositories {
        maven {
            url = uri(project.ext.mavenRepo)
        }
    }
}
